# Generated by Django 5.1.4 on 2025-01-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='date_uploaded',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.IntegerField(default=2020),
        ),
    ]
